kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  image: {{ image }}
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: {{ database.tier }}
        databases:
          - name: {{ database.name }}
            envVarPrefix:
              DATABASE
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: 250m
      memory: 512Mi
  progressDeadlineSeconds: 120
  azure:
    application:
      enabled: true
      allowAllUsers: true
      replyURLs:
        - "{{ ingress }}/callback"
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      external:
        - host: eux-case-store-q1.dev-fss-pub.nais.io
        - host: eux-case-store-q2.dev-fss-pub.nais.io
        - host: eux-case-store.prod-fss-pub.nais.io
        - host: eux-rina-api-q1.dev-fss-pub.nais.io
        - host: eux-rina-api-q2.dev-fss-pub.nais.io
        - host: eux-rina-api.prod-fss-pub.nais.io
      rules:
        - application: eux-nav-rinasak-q1
        - application: eux-nav-rinasak-q2
        - application: eux-nav-rinasak