spring:

  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 60000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true

  flyway:
    clean-on-validation-error: false
    clean-disabled: true

  thymeleaf:
    cache: false

  web:
    resources:
      cache:
        period: 0

  main:
    banner-mode: "off"

no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted-audience: ${AZURE_APP_CLIENT_ID}
      cookie-name: openam-idtoken

  client:
    registration:
      eux-case-store-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${CLIENT_CASESTORE_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

      eux-rina-api-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${CLIENT_RINAAPI_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

      eux-nav-rinasak-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${CLIENT_NAVRINASAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

      saf-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${CLIENT_SAF_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

endpoint:
  casestore: ${CLIENT_CASESTORE_ENDPOINT}
  rinaapi: ${CLIENT_RINAAPI_ENDPOINT}
  navrinasak: ${CLIENT_NAVRINASAK_ENDPOINT}
  saf: ${CLIENT_SAF_ENDPOINT}
